# fly.toml app configuration file generated for motorsport-cal-astro on 2023-10-22T23:33:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "motorsport-cal-astro"
primary_region = "ams"

[build]

[processes]
  app = ""
  cron = "bun run /app/src/test.ts"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024