name: Astro Studio

env:
    ASTRO_STUDIO_APP_TOKEN: ${{secrets.ASTRO_STUDIO_APP_TOKEN }}

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    DB:
        permissions:
            contents: read
            actions: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository and submodules
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              uses: jaid/action-npm-install@v1.2.1

            - name: Push changes to Astro Studio
              uses: withastro/action-studio@main
